# boolean type, the global switch for TOC in posts.
toc = true
# the avatar on sidebar, should be a relative path to /assets.
avatar = "img/commons/avatar.png"
author = "cfeki"
[params.license]
  enabled = true
  name = "CC BY-NC-SA 4.0"
  link = "https://creativecommons.org/licenses/by-nc-sa/4.0/"


[assets]
  # Self-hosted static assets, default to false. If true, the assets will be hosted on your own server.
  self_host = false

[social]
  name = "Chedi Feki"
  url = "https://github.com/chedifeki"

[[social.links]]
  type = "github"
  id = "chedifeki"
  icon = "fab fa-github"

[[social.links]]
  type = "twitter"
  id = "yourhandle"
  icon = "fab fa-twitter"

[[social.links]]
  type = "email"
  id = "your.email@example.com"
  icon = "fas fa-envelope"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
  noblank = true  # will not open in new window

[comments]
# Global switch for the post-comment system. [true | false]
enable = false
# The provider options are as follows: [disqus | utterances | giscus]
provider = ""

# Disqus options
[comments.disqus]
# fill with the Disqus shortname. â€º https://help.disqus.com/en/articles/1717111-what-s-a-shortname
shortname = ""
